[IMP] l10n_it_fiscalcode: adapt module to https://www.odoo-italia.org/documentazione/12.0/sviluppo/guidelines.html
Borruso/l10n-italy pull request #2
Opened 2020-11-20 14:44 UTC by tafaRU

2020-11-20 14:46 UTC, tafaRU commented
@Borruso attendiamo la review da parte di @primes2h

2020-11-21 16:43 UTC, primes2h requested changes
Grazie per la PR!

2020-11-21 16:43 UTC, primes2h commented on l10n_it_fiscalcode/readme/INSTALL.rst
> +Installa il modulo Python: `codicefiscale <https://pypi.python.org/pypi/codicefiscale>`_.
```suggestion
Installare il modulo Python: `codicefiscale <https://pypi.python.org/pypi/codicefiscale>`_.
```

2020-11-21 16:43 UTC, primes2h commented on l10n_it_fiscalcode/readme/USAGE.rst
> +Sulla scheda del partner fare clic sul pulsante *Calcola C.F.* per aprire il wizard relativo al calcolo
Essendo un acronimo i punti sono superflui.
Come da glossario *wizard* corrisponde alla *procedura guidata*.
https://www.odoo-italia.org/documentazione/12.0/traduzioni/glossari/generale.html

```suggestion
Sulla scheda del partner fare clic sul pulsante *Calcola CF* per aprire la procedura guidata relativa al calcolo
```

2020-11-21 16:43 UTC, primes2h commented on l10n_it_fiscalcode/readme/USAGE.rst
> +Go to Partner and click "Compute F.C." in order to open the wizard related to the fiscal code computation.
Vedi sopra, andrebbe modificata anche la stringa nel codice.

```suggestion
Go to Partner and click "Compute FC" in order to open the wizard related to the fiscal code computation.
```

2020-11-23 10:03 UTC, tafaRU commented
@primes2h grazie per i suggerimenti! Dovrei averli applicati tutti, potresti verificare?

2020-11-23 10:10 UTC, primes2h approved these changes
Ottimo, grazie! :+1:

2020-11-23 10:12 UTC, tafaRU commented
@Borruso ora puoi fare review anche tu :wink:

2020-11-23 10:26 UTC, merged